[book]
authors = ["loqusion"]
language = "en"
multilingual = false
src = "."
title = "Typix"

[output.html]
theme = "theme"
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/loqusion/typix"
edit-url-template = "https://github.com/loqusion/typix/edit/main/docs/{path}"
