name: Update flake lockfile
on:
  workflow_dispatch:
  # schedule:
  #   - cron: ""

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: typst-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: DeterminateSystems/update-flake-lock@v21
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
